### ISSUE TITLE
GPDD down

### ISSUE THREAD

**Issue by davidorme** [ropensci/rgpdd#9]
Hi,

I'm at Imperial and have had a hand in various incarnations of the GPDD. The website and API is now dead due to the usual combination of running costs and developers moving on. There is a chance that we might be able to get this up and running again, but it isn't going to happen soon. If it does, there might be some API changes (and we might need to find out what API access points you're expecting! The original developer is long gone!).

Cheers,
David

**Comment by sckott** [comment]
thanks! ping @cboettig

**Comment by cboettig** [comment]
@davidorme @sckott Thanks both.  A permanent archive of the GPDD was moved to KNB with help from the Imperial team and the folks at NCEAS, and can be found at the persistent DOI: http://doi.org/doi:10.5063/F1BZ63Z8.  This avoids all such issues with the API etc.  

The data at that DOI are provided in a standard open format (`.csv`), which should be more convenient than the previous Microsoft Access format available at the imperial website (and in older archives, e.g. https://doi.org/10.5063/AA/nceas.167.11).   Detailed metadata in EML accompanies each file. 

I'll updated the README here to indicate that.  No R package should be necessary now that the permanent archive in csv and EML.  

Cheers!

**Comment by davidorme** [comment]
OK, great. From the author list, that looks like the most recent version I know of.
